name: try-gmt
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.13
  - gmt=6.6.0
  - pygmt=0.17.0
  - jupyterlab=4.3.6
  - jupyter-offlinenotebook=0.3.1
  # Optional dependencies
  - geopandas=1.0.1
